CREATE TABLE IF NOT EXISTS `user` (
`id` int(11) NOT NULL auto_increment,
`nick` varchar(32) NOT NULL,
`pass` varchar(32) NOT NULL,
`sess` varchar(32) default NULL,
`activation` varchar(32) default NULL,
`ban` int(11) NOT NULL default '0',
`ban_pr` varchar(64) default NULL,
`ip` bigint(20) NOT NULL default '0',
`ip_cl` bigint(20) NOT NULL default '0',
`ip_xff` bigint(20) NOT NULL default '0',
`ua` varchar(32) default NULL,
`date_reg` int(11) NOT NULL default '0',
`date_aut` int(11) NOT NULL default '0',
`date_last` int(11) NOT NULL default '0',
`balls` int(11) NOT NULL default '0',
`rating` int(11) NOT NULL default '0',
`level` enum('0','1','2','3','4') NOT NULL default '0',
`group_access` int(10) unsigned NOT NULL default '0',
`pol` enum('0','1') NOT NULL default '1',
`url` varchar(64) NOT NULL default '/',
`show_url` enum('0','1') NOT NULL default '0',
`ank_g_r` int(4) default NULL,
`ank_m_r` int(2) default NULL,
`ank_d_r` int(2) default NULL,
`ank_city` varchar(32) default NULL,
`ank_o_sebe` varchar(512) default NULL,
`ank_icq` int(9) default NULL,
`ank_mail` varchar(32) default NULL,
`ank_n_tel` varchar(11) default NULL,
`ank_name` varchar(32) default NULL,
`agama` varchar(30) default NULL,
`asal` varchar(100) default NULL,
`tertarik` varchar(25) default NULL,
`hubungan` varchar(25) default NULL,
`negara` varchar(20) default NULL,
`aktivitas` varchar(100) default NULL,
`minat` varchar(100) default NULL,
`musik` varchar(35) default NULL,
`tv` varchar(35) default NULL,
`film` varchar(35) default NULL,
`buku` varchar(35) default NULL,
`kutipan` varchar(75) default NULL,
`bio` varchar(512) default NULL,
`sekolah` varchar(100) default NULL,
`kampus` varchar(50) default NULL,
`kerja` varchar(50) default NULL,
`jabatan` varchar(20) default NULL,
`set_time_chat` int(11) default '30',
`set_p_str` int(11) default '7',
`set_show_icon` enum('0','1','2') default '1',
`set_translit` enum('0','1') NOT NULL default '1',
`set_files` enum('0','1') NOT NULL default '0',
`set_timesdvig` int(11) NOT NULL default '0',
`set_news_to_mail` enum('0','1') NOT NULL default '0',
`set_show_mail` enum('0','1') NOT NULL default '0',
`set_them` varchar(32) default 'default',
`set_them2` varchar(32) default 'web',
`meteo_country` int(11) NOT NULL default '0',
`autorization` enum('0','1') NOT NULL default '0',
PRIMARY KEY  (`id`),
UNIQUE KEY `nick` (`nick`),
KEY `url` (`url`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
